### PR TITLE
DifferencePercentageIndicator #906 removed instance variable #1051 set unstable bars

### LINKED ISSUE #906: Eliminate class instance variables from indicators
We need to eliminate all usages of class instance variables from cachable indicators that store context information that depend on an index. 

This issue is here **to list all those indicators** and afterwards to create dedicated PR's to remove those class instance variables. If anyone knows a better solution, ideas are welcome.

See:
- https://github.com/ta4j/ta4j/issues/904#issuecomment-1292467096
- https://github.com/ta4j/ta4j/issues/902#issuecomment-1289344468

Maybe, we should also include a sentence in the ta4j documentation like:
_"When developing a cached indicator, then do **not** use class instance variable when calculating the indicator value, because ..."_

EDIT 1: Using this top commentary for summary of findings:
- [x] TrailingStopLossRule (currentStopLossLimitActivation)
- [x] ThreeBlackCrowsIndicator (whiteCandleIndex)
- [x] ThreeWhiteSoldiersIndicator (blackCandleIndex)
- [x] DifferencePercentageIndicator (lastNotification)
- [x] SimpleLinearRegressionIndicator (slope, intercept) (not a bug calculateRegressionLine get called in every iteration)
- [x] ParabolicSarIndicator

EDIT 2: Packages that have been reviewed:
- [x] _default_
- [x] utils
- [x] num
- [x] aggregator
- [x] reports
- [x] indicators
- [x] candles
- [x] bollinger
- [x] adx
- [x] aroon
- [x] helpers
- [x] rules
- [x] volume
- [x] statistics
- [x] pivotpoints
- [x] numeric
- [x] keltner
- [x] ichimoku
- [x] criteria
- [x] helpers
- [x] pnl
- [x] analysis
- [x] cost

### LINKED ISSUE #1051: Check each indicator if the default `unstableBars` is correct
This is a precondition for https://github.com/ta4j/ta4j/issues/947.

Unfortunately, we need to go through all the indicators and check if their `Indicator#getUnstableBars()` returns the right value. 

I won't be able to do this on my own, so I need help from the community, who are well versed in the relevant indicators. I think solving the issue will take some time before anyone who knows the indicator in question gets in touch. But we just have to start.

I know, the number of unstable bars to consider for any indicator, can vary depending on several factors such as the timeframe, market conditions, and individual trading strategies. However, at least a minimum number of bars may need to be reached before the indicator returns **CORRECT VALUES**. It is precisely such unstable bars that I am talking about in this issue, nothing else!

I think, we do it like this:

(1) Anyone is free to do a PR with the corrected `Indicator#getUnstableBars()` and link their PR to this issue. I will then mark the appropriate checkbox as done after merged.
(2) For confirmation that an existing `Indicator#getUnstableBars()` is already correct, just write a short answer here. I will then mark the appropriate checkbox as done.
(3) For each indicator checked, we should improve the javadoc of that indicator (e.g. `@return barCount `). With this we can also see (in the source code) that this indicator has already been checked and which indicators have not yet been checked (that is then all indicators where a javadoc with a specific `@return ...` is missing.

Here all indicators which must be checked:

*********** ADX: 
- [ ] `adx/`ADXIndicator.java
- [ ] `adx/`DXIndicator.java
- [ ] `adx/`MinusDIIndicator.java
- [ ] `adx/`MinusDMIndicator.java
- [ ] `adx/`PlusDIIndicator.java
- [ ] `adx/`PlusDMIndicator.java

*********** AROON: 
- [ ] `aroon/`AroonDownIndicator.java
- [ ] `aroon/`AroonOscillatorIndicator.java
- [ ] `aroon/`AroonUpIndicator.java

*********** AVERAGE: 
- [ ] `average/`DistanceFromMAIndicator.java
- [ ] `average/`DoubleEMAIndicator.java
- [ ] `average/`EMAIndicator.java
- [ ] `average/`HMAIndicator.java
- [ ] `average/`KAMAIndicator.java
- [ ] `average/`LWMAIndicator.java
- [ ] `average/`MACDIndicator.java
- [ ] `average/`MMAIndicator.java
- [x] `average/`SMAIndicator.java (`unstableBars = barCount`)
- [ ] `average/`TripleEMAIndicator.java
- [ ] `average/`WMAIndicator.java
- [ ] `average/`ZLEMAIndicator.java

*********** BOLLINGER: 
- [ ] `bollinger/`BollingerBandFacade.java
- [ ] `bollinger/`BollingerBandsLowerIndicator.java
- [ ] `bollinger/`BollingerBandsMiddleIndicator.java
- [ ] `bollinger/`BollingerBandsUpperIndicator.java
- [ ] `bollinger/`BollingerBandWidthIndicator.java
- [ ] `bollinger/`PercentBIndicator.java

*********** CANDLES: 
- [ ] `candles/`BearishEngulfingIndicator.java
- [ ] `candles/`BearishHaramiIndicator.java
- [ ] `candles/`BullishEngulfingIndicator.java
- [ ] `candles/`BullishHaramiIndicator.java
- [ ] `candles/`DojiIndicator.java
- [ ] `candles/`LowerShadowIndicator.java
- [ ] `candles/`RealBodyIndicator.java
- [x] `candles/`ThreeBlackCrowsIndicator.java (`unstableBars = 4`)
- [x] `candles/`ThreeWhiteSoldiersIndicator.java (`unstableBars = 4`)
- [ ] `candles/`UpperShadowIndicator.java

*********** DONCHIAN:
- [ ] `donchian/`DonchianChannelLowerIndicator.java
- [ ] `donchian/`DonchianChannelMiddleIndicator.java
- [ ] `donchian/`DonchianChannelUpperIndicator.java

*********** HELPERS:
- [x] `helpers/`AmountIndicator.java (`unstableBars = 0`)
- [x] `helpers/`BooleanTransformIndicator.java (`unstableBars = 0`)
- [x] `helpers/`CloseLocationValueIndicator.java (`unstableBars = 0`)
- [x] `helpers/`ClosePriceDifferenceIndicator.java (`unstableBars = 1`)
- [x] `helpers/`ClosePriceIndicator.java (`unstableBars = 0`)
- [x] `helpers/`ClosePriceRatioIndicator.java (`unstableBars = 1`)
- [x] `helpers/`CombineIndicator.java (`unstableBars = 0`)
- [x] `helpers/`ConstantIndicator.java (`unstableBars = 0`)
- [x] `helpers/`ConvergenceDivergenceIndicator.java (`unstableBars = barCount`)
- [ ] `helpers/`CrossIndicator.java
- [x] `helpers/`DateTimeIndicator.java (`unstableBars = 0`)
- [x] `helpers/`DifferencePercentageIndicator.java (`unstableBars = 1`)
- [x] `helpers/`FixedBooleanIndicator.java (`unstableBars = 0`)
- [x] `helpers/`FixedDecimalIndicator.java (`unstableBars = 0`)
- [x] `helpers/`FixedIndicator.java (`unstableBars = 0`)
- [x] `helpers/`GainIndicator.java (`unstableBars = 1`)
- [x] `helpers/`HighestValueIndicator.java (`unstableBars = barCount`)
- [x] `helpers/`HighPriceIndicator.java (`unstableBars = 0`)
- [x] `helpers/`LossIndicator.java (`unstableBars = 1`)
- [x] `helpers/`LowestValueIndicator.java (`unstableBars = barCount`)
- [x] `helpers/`LowPriceIndicator.java (`unstableBars = 0`)
- [x] `helpers/`MedianPriceIndicator.java (`unstableBars = 0`)
- [x] `helpers/`NumIndicator.java (`unstableBars = 0`)
- [x] `helpers/`OpenPriceIndicator.java (`unstableBars = 0`)
- [x] `helpers/`PreviousValueIndicator.java (`unstableBars = n`-th previous index)
- [ ] `helpers/`SumIndicator.java
- [x] `helpers/`TradeCountIndicator.java (`unstableBars = 0`)
- [ ] `helpers/`TransformIndicator.java
- [x] `helpers/`TRIndicator.java (`unstableBars = 1`)
- [x] `helpers/`TypicalPriceIndicator.java (`unstableBars = 0`)
- [x] `helpers/`UnstableIndicator.java (`unstableBars = unstableBars`)
- [x] `helpers/`VolumeIndicator.java  (`unstableBars = barCount`)

*********** ICHIMOKU:
- [ ] `ichimoku/`IchimokuChikouSpanIndicator.java
- [ ] `ichimoku/`IchimokuKijunSenIndicator.java
- [ ] `ichimoku/`IchimokuLineIndicator.java
- [ ] `ichimoku/`IchimokuSenkouSpanAIndicator.java
- [ ] `ichimoku/`IchimokuSenkouSpanBIndicator.java
- [ ] `ichimoku/`IchimokuTenkanSenIndicator.java

*********** KELTNER:
- [ ] `keltner/`KeltnerChannelFacade.java
- [ ] `keltner/`KeltnerChannelLowerIndicator.java
- [ ] `keltner/`KeltnerChannelMiddleIndicator.java
- [ ] `keltner/`KeltnerChannelUpperIndicator.java

*********** NUMERIC:
- [ ] `numeric/`BinaryOperation.java
- [ ] `numeric/`NumericIndicator.java
- [ ] `numeric/`UnaryOperation.java

*********** PIVOTPOINTS:
- [ ] `pivotpoint/`DeMarkPivotPointIndicator.java
- [ ] `pivotpoint/`DeMarkReversalIndicator.java
- [ ] `pivotpoint/`FibonacciReversalIndicator.java
- [ ] `pivotpoint/`PivotPointIndicator.java
- [ ] `pivotpoint/`StandardReversalIndicator.java

*********** STATISTICS:
- [ ] `statistics/`CorrelationCoefficientIndicator.java
- [ ] `statistics/`CovarianceIndicator.java
- [ ] `statistics/`MeanDeviationIndicator.java
- [ ] `statistics/`PearsonCorrelationIndicator.java
- [ ] `statistics/`PeriodicalGrowthRateIndicator.java
- [ ] `statistics/`SigmaIndicator.java
- [ ] `statistics/`SimpleLinearRegressionIndicator.java
- [ ] `statistics/`StandardDeviationIndicator.java
- [ ] `statistics/`StandardErrorIndicator.java
- [ ] `statistics/`VarianceIndicator.java

*********** SUPERTREND:
- [ ] `supertrend/`SuperTrendIndicator.java
- [ ] `supertrend/`SuperTrendLowerBandIndicator.java
- [ ] `supertrend/`SuperTrendUpperBandIndicator.java

*********** VOLUME:
- [ ] `volume/`AccumulationDistributionIndicator.java
- [ ] `volume/`ChaikinMoneyFlowIndicator.java
- [ ] `volume/`ChaikinOscillatorIndicator.java
- [ ] `volume/`IIIndicator.java
- [ ] `volume/`MVWAPIndicator.java
- [ ] `volume/`NVIIndicator.java
- [ ] `volume/`OnBalanceVolumeIndicator.java
- [ ] `volume/`PVIIndicator.java
- [ ] `volume/`ROCVIndicator.java
- [ ] `volume/`VWAPIndicator.java
- [ ] `volume/`TimeSegmentedVolumeIndicator.java

*********** ETC.:
- [ ] AccelerationDecelerationIndicator.java
- [ ] ATRIndicator.java
- [ ] AwesomeOscillatorIndicator.java
- [ ] CCIIndicator.java
- [ ] ChandelierExitLongIndicator.java
- [ ] ChandelierExitShortIndicator.java
- [ ] ChopIndicator.java
- [ ] CMOIndicator.java
- [ ] CoppockCurveIndicator.java
- [ ] DPOIndicator.java
- [ ] FisherIndicator.java
- [ ] KSTIndicator.java
- [ ] MassIndexIndicator.java
- [ ] ParabolicSarIndicator.java
- [ ] PPOIndicator.java
- [ ] PVOIndicator.java
- [ ] RAVIIndicator.java
- [ ] ROCIndicator.java
- [ ] RSIIndicator.java
- [ ] RWIHighIndicator.java
- [ ] RWILowIndicator.java
- [ ] StochasticOscillatorDIndicator.java
- [ ] StochasticOscillatorKIndicator.java
- [ ] StochasticRSIIndicator.java
- [ ] UlcerIndexIndicator.java
- [ ] WilliamsRIndicator.java

### PR DESCRIPTION
**Pull request by team172011**
Fixes #906
Fixes #1051 

Changes proposed in this pull request:
- re-calculate instance variable from indicator
- set unstable bars

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

File: ta4j-core/src/main/java/org/ta4j/core/indicators/helpers/DifferencePercentageIndicator.java [hunk 1]
```diff
@@ -79,25 +79,50 @@ public DifferencePercentageIndicator(Indicator<Num> indicator, Num percentageThr
 
     @Override
     protected Num calculate(int index) {
+        int beginIndex = getBarSeries().getBeginIndex();
+        if (beginIndex > index) {
+            return NaN.NaN;
+        }
+
         Num value = indicator.getValue((index));
```
Comment (nimo23) [inline ta4j-core/src/main/java/org/ta4j/core/indicators/helpers/DifferencePercentageIndicator.java]: remove the double braces in `((index))`
